name: github CI(Continuous Integration)
on: push
jobs:
  build-project:
    name: Build-Project # job name which will show in Github
    runs-on: ubuntu-latest # define the OS which the jobs runs on, must be defined for each job not the whole workflow
    # container: node:17.6.0 # setup node version in docker container
    steps: # define a list of steps of this job
      - name: Checkout Codes # clone all Github codes to container
        uses: actions/checkout@v2
      - name: Get Verilog Top # cat all verilog files into one file
        run: |
          ls ${{ github.workspace }}/vsrc  
          touch top.v
          cat ${{ github.workspace }}/vsrc/*.v > top.v
          cat top.v
      - name: Upload Verilog File # upload top.v file, the file can be found in Github Actions Page, we can download it
        uses: actions/upload-artifact@v2
        with:
          name: verilog-file # this name will be used later
          path: top.v
  release-project:
    name: Release-Project
    runs-on: ubuntu-latest
    needs: build-project # dependency project
    steps:
      - name: Download Verilog content
        uses: actions/download-artifact@v2
        with:
          name: verilog-file # set download target
      - name: View content # show all contents in download file
        run: ls -R
