name: trigger by REST API
on: 
  workflow_dispatch:
    inputs:
        tags:
          description: 'Test scenario tags'
          required: true
          type: string
jobs:
  build-project: # first job: create Verilog file and upload to Github Actions Page
    permissions: write-all # git permissions to this job or you can't create a release in the following step
    name: build-project # job name which will show in Github
    runs-on: ubuntu-latest # define the OS which the jobs runs on, must be defined for each job not the whole workflow
    # container: node:17.6.0 # setup node version in docker container
    steps: # define a list of steps of this job
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tags }} 
